// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Test text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.test_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  test_text: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = NavLinksSlice | NestedNavLinksSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Header Title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.header_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomePageDocumentDataSlicesSlice = HeroBannerSlice | VideoBannerSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Home Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type LandingPageDocumentDataSlicesSlice = never;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | HomePageDocument
  | LandingPageDocument;

/**
 * Primary content in *HeroBanner → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Background Image field in *HeroBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Banner Title field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.banner_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  banner_title: prismic.KeyTextField;

  /**
   * Banner Subtitle field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.banner_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  banner_subtitle: prismic.KeyTextField;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Primary content in *NavLinks → Primary*
 */
export interface NavLinksSliceDefaultPrimary {
  /**
   * Label field in *NavLinks → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_links.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Page field in *NavLinks → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_links.primary.page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page: prismic.LinkField;
}

/**
 * Default variation for NavLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavLinksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavLinks*
 */
type NavLinksSliceVariation = NavLinksSliceDefault;

/**
 * NavLinks Shared Slice
 *
 * - **API ID**: `nav_links`
 * - **Description**: NavLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavLinksSlice = prismic.SharedSlice<
  "nav_links",
  NavLinksSliceVariation
>;

/**
 * Primary content in *NestedNavLinks → Primary*
 */
export interface NestedNavLinksSliceDefaultPrimary {
  /**
   * Label field in *NestedNavLinks → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nested_nav_links.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Page field in *NestedNavLinks → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nested_nav_links.primary.page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page: prismic.LinkField;
}

/**
 * Primary content in *NestedNavLinks → Items*
 */
export interface NestedNavLinksSliceDefaultItem {
  /**
   * Page field in *NestedNavLinks → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nested_nav_links.items[].page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page: prismic.LinkField;
}

/**
 * Default variation for NestedNavLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NestedNavLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NestedNavLinksSliceDefaultPrimary>,
  Simplify<NestedNavLinksSliceDefaultItem>
>;

/**
 * Slice variation for *NestedNavLinks*
 */
type NestedNavLinksSliceVariation = NestedNavLinksSliceDefault;

/**
 * NestedNavLinks Shared Slice
 *
 * - **API ID**: `nested_nav_links`
 * - **Description**: NestedNavLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NestedNavLinksSlice = prismic.SharedSlice<
  "nested_nav_links",
  NestedNavLinksSliceVariation
>;

/**
 * Primary content in *VideoBanner → Primary*
 */
export interface VideoBannerSliceDefaultPrimary {
  /**
   * Video Embed HTML field in *VideoBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_banner.primary.video_embed_html
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_embed_html: prismic.KeyTextField;
}

/**
 * Default variation for VideoBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoBanner*
 */
type VideoBannerSliceVariation = VideoBannerSliceDefault;

/**
 * VideoBanner Shared Slice
 *
 * - **API ID**: `video_banner`
 * - **Description**: VideoBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBannerSlice = prismic.SharedSlice<
  "video_banner",
  VideoBannerSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      NavLinksSlice,
      NavLinksSliceDefaultPrimary,
      NavLinksSliceVariation,
      NavLinksSliceDefault,
      NestedNavLinksSlice,
      NestedNavLinksSliceDefaultPrimary,
      NestedNavLinksSliceDefaultItem,
      NestedNavLinksSliceVariation,
      NestedNavLinksSliceDefault,
      VideoBannerSlice,
      VideoBannerSliceDefaultPrimary,
      VideoBannerSliceVariation,
      VideoBannerSliceDefault,
    };
  }
}
