// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_banner: dynamic(() => import("./HeroBanner")),
  nav_links: dynamic(() => import("./NavLinks")),
  nested_nav_links: dynamic(() => import("./NestedNavLinks")),
  video_banner: dynamic(() => import("./VideoBanner")),
};
